### ISSUE TITLE
iOS10 Cannot OAuth Solution - iOS10无法进行授权的解决方案

### ISSUE THREAD

**Issue by jkpang** [PPHubApp/PPHub-Feedback#243]
GitHub officially limits the operation of the first login authorization for iOS10 and below. The following is the solution:

1. Copy the link below to authorize on your iOS11+ device or the latest version of Safari/Chrome/Firefox.
    **Public only:** https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications
    **Public library + private:** https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,repo,notifications
2. Once the authorization is successful, you can log in to your iOS10 device.

GitHub官方限制了iOS10及以下系统首次登录授权的操作，以下是解决方案：   
1. 复制以下链接，在iOS11+设备或最新版本的Safari/Chrome/Firefox浏览器进行授权。
    **仅公开库：** https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,public_repo,notifications
   **公开库 + 私有库：** https://github.com/login/oauth/authorize?client_id=5d79469d95f67fe366c9&scope=user,repo,notifications   
2. 授权成功后，即可在您的iOS10设备上登录使用。    

![QQ20190313-174605](https://user-images.githubusercontent.com/17583451/54269231-ef70f580-45b7-11e9-86b1-eede00cfaad2.png)

**Comment by CL-Jeremy** [comment]
> Copy the link below to authorize on your iOS11+ device or the latest version of Safari/Chrome/Firefox.

And for those who do not own such devices, not even computers (legacy OS users who cannot/do not want to upgrade or install up-to-date 3rd party browsers), I would suggest doing MitM to spoof user agent headers. My personal choice for doing this is **mitmproxy**:

1. [Download](https://mitmproxy.org/) and run `mitmproxy --setheaders/<pattern>/User-Agent/<quoted UA string>`, such as
```mitmproxy --setheaders /github.com/User-Agent/"Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like macOS) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/12.0 Mobile/14A5335d Safari/602.1.50"```
2. On the iOS device, configure proxy options in Wi-Fi settings (default: use the local IP address of your computer with port 8080)
3. Visit [mitm.it](http://mitm.it) from iOS device and import the CA certificate for mitmproxy (use your lockscreen passcode)
4. Trust that certificate as per [Apple's official guite](https://support.apple.com/HT204477)
5. Enjoy GitHub on deprecated browsers (this guide works for deprecated browsers in general, such as Safari Desktop < 11.0 which works in theory but intentionally crippled, though rightfully IMHO)
6. You may turn off trust of mitmproxy CA after use (flip back the switch from step 2), and of course turn off proxy settings after closing mitmproxy 😂

P.S. This guide works in general for any GitHub OAuth app, but since the developer has kindly provided the app ID, it is sufficient to proxy your desktop browser only and use the OAuth links above from directly from your computer.

对于手边没有 iOS 11 或以上系统设备，或是电脑上只有陈旧系统却因为种种情况不愿或不能升级浏览器的朋友们，建议临时搭建中间人代理。个人推荐 mitmproxy，使用很方便：
1. [安装](https://mitmproxy.org/)运行 `mitmproxy`，加入 setheaders 选项替换 User-Agent 值，如 ```mitmproxy --setheaders /github.com/User-Agent/"Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like macOS) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/12.0 Mobile/14A5335d Safari/602.1.50"```
2. 在 iOS 设备上对 Wi-Fi 访问设置代理，默认为运行代理软件的电脑 IP 地址和 8080 端口
3. 还是在 iOS 设备上，访问 [mitm.it](http://mitm.it) 下载并导入证书（输入锁屏 PIN）
4. 参考[官方教程](https://support.apple.com/HT204477)在设置-通用-关于本机里最下方信任 mitmproxy 根证书
5. 尽情享用 GitHub（不但可以从所有浏览器和应用内打开，更可以用于其他平台被 GitHub 强制“不兼容”的浏览器，比如无法升级 Safari 11.0 的 Yosemite）
6. 用完最好回去第二步的地方解除信任根证书（然后退出 mitmproxy 了自然也要把代理设置取消 😂）

另：写完才反应过来开发者提供的就是带应用 ID 的直链，那么可以直接在同一台电脑上对不兼容浏览器做代理，然后直接点击上面的 OAuth 链接授权即可，少些折腾。

**Comment by jkpang** [comment]
Great!
厉害了，向大佬低头 @CL-Jeremy
